name: Build and Publish 'anix-api-prox' to Docker Hub

on:
  push:
    branches:
      - V3
    paths:
      - "api-prox/*.ts"
      - "!api-prox/hooks/*"
      - "!api-prox/episode/*"
      - "api-prox/Dockerfile"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Dynamically set 'tag' environment variable
        run: echo "tag=$(date +'%d-%m-%Y')" >> $GITHUB_ENV
      - name: Build Image
        run: |
          cd ./api-prox
          docker build . -t radiquum/anix-api-prox:latest
          docker tag radiquum/anix-api-prox:latest radiquum/anix-api-prox:${{ env.tag }}
      - name: Publish Image
        run: |
          docker login -u radiquum -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push radiquum/anix-api-prox:latest
          docker push radiquum/anix-api-prox:${{ env.tag }}
