name: Build and Publish 'anix-player-parsers' to Docker Hub

on:
  push:
    branches:
      - V3
    paths:
      - "player-parser/*.ts"
      - "player-parser/Dockerfile"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Dynamically set 'tag' environment variable
        run: echo "tag=$(date +'%d-%m-%Y')" >> $GITHUB_ENV
      - name: Build Image
        run: |
          cd ./player-parser
          docker build . -t radiquum/anix-player-parser:latest
          docker tag radiquum/anix-player-parser:latest radiquum/anix-player-parser:${{ env.tag }}
      - name: Publish Image
        run: |
          docker login -u radiquum -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push radiquum/anix-player-parser:latest
          docker push radiquum/anix-player-parser:${{ env.tag }}
